-- IS pipeline redesign — durable persistence for approved templates, audit history, and
-- source-PDF retention. Apply in Supabase SQL editor (service role) — the app's anon key
-- cannot run DDL. Safe to re-run (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).

-- 1) The approved, human-confirmed per-IS template (versioned). Drives the report.
CREATE TABLE IF NOT EXISTS is_report_templates (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isNumber"   text NOT NULL,
  version      integer NOT NULL DEFAULT 1,
  template     jsonb NOT NULL,              -- { parameterizationDims, dimensionOptions, dimensionGrid, parameters[] }
  approved     boolean NOT NULL DEFAULT false,
  "approvedBy" text,
  "approvedAt" timestamptz,
  "createdAt"  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT is_report_templates_is_version_key UNIQUE ("isNumber", version)
);
CREATE INDEX IF NOT EXISTS is_report_templates_isnumber_idx ON is_report_templates ("isNumber");

-- 2) Audit trail of every extraction / approval / rescan — powers the rescan diff + traceability.
CREATE TABLE IF NOT EXISTS is_extraction_history (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "isNumber"   text NOT NULL,
  version      integer,
  kind         text NOT NULL CHECK (kind IN ('extract', 'approve', 'rescan')),
  payload      jsonb,                       -- snapshot: params, completeness report, confidence, diff
  "createdAt"  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS is_extraction_history_isnumber_idx ON is_extraction_history ("isNumber");

-- 3) Retain the source material so re-verify / re-structure never needs a re-upload.
ALTER TABLE is_standards_vault ADD COLUMN IF NOT EXISTS "fullText"      text;   -- whole-doc transcription
ALTER TABLE is_standards_vault ADD COLUMN IF NOT EXISTS "sourcePdfPath" text;   -- path in the is-pdfs storage bucket
ALTER TABLE is_standards_vault ADD COLUMN IF NOT EXISTS "completeness"  jsonb;  -- last completeness report (expected vs got)

-- 4) Source-PDF storage bucket (run once; or create "is-pdfs" via Dashboard → Storage).
--    insert into storage.buckets (id, name, public) values ('is-pdfs','is-pdfs', false)
--    on conflict (id) do nothing;

-- NOTE: keep RLS consistent with the rest of the project (see disable_rls_all_tables.sql).
-- If RLS is enabled project-wide, add policies for these two tables to match.
